#!/usr/bin/env bash

########################################################
#Simple script to put updated files in place.
#
version="1.0.0"
#
#
# History:
#
# * DATE - v1.0.0 - First Creation
#
########################################################



diff bash_aliases /home/$USER/.bash_aliases
if [ $? -eq 0 ]; then
	echo "bash_aliases does not need to be copied."
else
	#cp bash_aliases /home/$USER/.bash_aliases
	cp bash_aliases /home/$USER/bin/mydotfiles/files/.bash_aliases
	echo "New bash_aliases copied."
fi

diff ssh_setup /home/$USER/bin/mydotfiles/files/.ssh_setup
if [ $? -eq 0 ]; then
	echo "ssh_config does not need to be copied."
else
	cp ssh_setup /home/$USER/bin/mydotfiles/files/.ssh_setup
	echo "New ssh config copied."
fi

diff  vimrc /home/$USER/.vimrc
if [ $? -eq 0 ]; then
	echo "vimrc does not need to be copied."
else
	cp vimrc /home/$USER/.vimrc
	echo "New vimrc copied."
fi
