#!/bin/bash

#Read and source our dotfiles

#for DOTFILE in `find /home/$USER/test/`
#do
#	[ -f "$DOTFILE" ] && ls -l "$DOTFILE"
#done

##
#Add to bashrc
#Read and source our dotfiles
#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases > /dev/null 2>&1
#fi
#Future?
for DOTFILE in `find /home/$USER/bin/mydotfiles/files`
do
	[ -f "$DOTFILE" ] && source "$DOTFILE" > /dev/null 2>&1
done

