#!/bin/bash

#Read and source our dotfiles

#for DOTFILE in `find /home/$USER/test/`
#do
#	[ -f "$DOTFILE" ] && ls -l "$DOTFILE"
#done

##
#Add to bashrc
# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

#Read and source our dotfiles
# These files also in ssh setup
# and other configs

#old method. remove?
#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases > /dev/null 2>&1
#fi

for DOTFILE in `find /home/$USER/bin/mydotfiles/files`
do
	[ -f "$DOTFILE" ] && source "$DOTFILE" > /dev/null 2>&1
done
